// Resume data — 王子墨 (Dawn / dawnwzm) — AIGC 产品运营
window.RESUME_DATA = {
  identity: {
    handle: "dawn",
    name: "王子墨",
    title: "aigc 产品运营 · ai 工作流设计师",
    tag: "ex-360 · ex-damo · ex-liweike",
    location: "Beijing",
    contact: { phone: "156 0026 5463", email: "dawnwzm@gmail.com" },
    languages: ["中文母语", "韩语 TOPIK 6", "英语流利"],
    keywords: ["aigc 多模态", "agent 工作流", "comfyui", "vibe coding", "视频/图像生成"],
  },
  hero_lines: [
    { cmd: "whoami",               out: "王子墨 — aigc 产品运营 · ai 工作流设计师" },
    { cmd: "cat ~/now.log",        out: "[2026.05] 在 360 集团做多模态 ai 玩法的模板体系与生产链路" },
    { cmd: "cat ~/north_star.md",  out: "从内容创作到 ai 工作流构建 · 用产品思维驱动 aigc 落地与规模化生产" },
    { cmd: "ls ~/experience/",     out: "360.log  寻光.log  李未可.log  保利大丰剧院.log  东国大学.log" },
  ],
  experiences: [
    {
      id: "360",
      year: "2025.12 — now",
      company: "360 集团 · 快剪辑 / 美片",
      company_zh: "三六零安全科技",
      role: "ai 产品运营专家 / ai 玩法设计师",
      location: "Beijing",
      bullets: [
        "为解决多模态 APP 产品内容生产瓶颈，独立设计 AI 工作流体系方向与生产路径",
        "为解决视频模板业务制作周期长问题，用 Vibe Coding 搭建「逆推视频 Mac App」",
        "主导 10+ 外部模型的评测、效果优化与接入整合",
      ],
      tags: ["aigc", "agent", "comfyui", "vibe-coding", "模板体系"],
      images: [
        "assets/works/360-work-1.jpg",
        "assets/works/360-work-2.jpg",
        "assets/works/360-work-3.png",
      ],
      buildingId: "360",
      stats: { templates: 200, conv: 180, retention: 30, models: 10 },
      stat_labels: {
        templates: { label: "模板", suffix: "+" },
        conv: { label: "新用户转化", suffix: "%↑" },
        retention: { label: "次留", suffix: "%↑" },
        models: { label: "外部模型", suffix: "+" },
      },
    },
    {
      id: "damo",
      year: "2024.11 — 2025.08",
      company: "阿里达摩院 · 寻光",
      company_zh: "xunguang.com · ai 视频生成",
      role: "ai 产品运营 / 高级 ux 设计师",
      location: "Hangzhou",
      bullets: [
        "区分 b/c 端用户需求，建立双端差异化 ai 视频模板库，累计 100+ 模板",
        "通过 sop 模板化与算法优化，压缩视频生成与交付流程 200+ 小时",
        "主导模板体系从 0 → 1 规范化建设：脚本结构、生成参数、质检标准",
        "主导「视频裂变」「3d 运镜」「3d 动作捕捉」核心功能调研评测落地",
        "输出 30+ 深度调研报告，视频生成准确率从 75% → 92%",
        "基于 2w+ 内测用户设计增长与留存策略，策划 ugc 挑战赛与官网教学专区",
      ],
      tags: ["aigc", "ai-video", "0→1", "b端/c端", "ux"],
      buildingId: "ali",
      stats: { templates: 100, hours: 200, accuracy: 92, users: 20000 },
      stat_labels: {
        templates: { label: "模板", suffix: "+" },
        hours: { label: "交付提速", suffix: "h↓" },
        accuracy: { label: "生成准确率", suffix: "%" },
        users: { label: "内测用户", suffix: "+" },
      },
    },
    {
      id: "liweike",
      year: "2023.10 — 2024.08",
      company: "杭州李未可科技",
      company_zh: "ai + ar 眼镜",
      role: "编导 / 导演",
      location: "Hangzhou",
      bullets: [
        "独立负责产品宣传片、短视频、信息流广告的脚本 / 拍摄 / 剪辑",
        "针对抖音、小红书、b站定制内容策略，带队全年发布 1000+ 视频",
        "单条视频最高达成 20w+ 转化",
        "将 aigc 工具与实拍内容结合，融合热点产出账号风格内容",
        "策划公司虚拟 ip 人设，独立完成短剧《未世清醒》3 集脚本与分镜",
        "尝试 ai 分镜生成与 cg 动效结合，跨部门推动内容落地",
      ],
      tags: ["编导", "短视频", "aigc-content", "虚拟ip", "ar"],
      buildingId: "liweike",
      stats: { videos: 1000, conv: 200000 },
      stat_labels: {
        videos: { label: "视频发布", suffix: "+" },
        conv: { label: "单条最高转化", suffix: "+" },
      },
    },
    {
      id: "baoli",
      year: "2022.03 — 2023.03",
      company: "保利大丰剧院",
      company_zh: "Poly Theater · Dafeng",
      role: "运营主管",
      location: "Jiangsu",
      bullets: [
        "统筹并制定全年运营计划，带领 12 人团队完成剧院运营目标",
        "全年上座率超额达成 30%，一年内剧院上座率提升 86%",
        "制定内容营销策略，建联 300+ koc、50+ kol 资源库",
      ],
      tags: ["剧院运营", "团队", "kol/koc", "内容营销"],
      buildingId: "theater",
      stats: { team: 12, occupancy: 86, koc: 300, kol: 50 },
      stat_labels: {
        team: { label: "团队", suffix: "人" },
        occupancy: { label: "上座率", suffix: "%↑" },
        koc: { label: "koc", suffix: "+" },
        kol: { label: "kol", suffix: "+" },
      },
    },
    {
      id: "dgu",
      year: "2019.03 — 2022.03",
      company: "韩国东国大学",
      company_zh: "Dongguk University · 公演艺术经营",
      role: "硕士 · m.s. arts management",
      location: "Seoul",
      bullets: [
        "专业课程：剧场制片、市场营销、大众传播学、剧本制作",
        "具备内容策划、演出运营、传播策略与用户沟通基础",
        "韩语 topik 6 级，具备跨文化沟通与资料调研能力",
      ],
      tags: ["academic", "arts-management", "korea"],
      buildingId: null,
    },
  ],
  projects: [
    {
      id: "prompt-reverse",
      name: "prompt 逆推 web app",
      sub: "vibe coding · 独立研发",
      desc: "发现现有工具无法从成品视频逆推 prompt 的痛点。独立完成需求分析、产品设计与工具研发，显著降低 ai 内容模板复用成本，直接服务于 360 aigc 模板规模化生产链路。",
    },
    {
      id: "ae-pipeline",
      name: "ae 自动化批量生产链路",
      sub: "mac app → cep agent → ae 批量模板",
      desc: "独立搭建「视频逆推 → 脚本提取 → ae 批量输出」全链路。推动 ai 大模型与 ae 工具链深度结合，模板效率 +70%，单模板 2h → 40min，支持热点规模化复刻。",
    },
    {
      id: "xunguang-template",
      name: "寻光 ai 视频模板体系",
      sub: "阿里达摩院 · b/c 双端",
      desc: "建立 b/c 端差异化模板库，累计 100+ 模板。sop + 算法优化压缩 200+ 交付小时。输出 30+ 调研报告，推动准确率 75% → 92%。",
    },
  ],
  skills: {
    "ai 工具链":   ["comfyui", "agent 工作流", "vibe coding", "prompt engineering", "ae 自动化"],
    "aigc 平台":   ["midjourney", "runway", "kling", "sora", "即梦", "可灵", "海螺", "豆包"],
    "产品能力":   ["用户需求分析", "功能调研评测", "模型评估调优", "数据分析", "prd 撰写"],
    "内容能力":   ["短视频脚本", "分镜设计", "多平台内容策略", "ai + 实拍混合生产"],
  },
  contact: {
    phone: "156 0026 5463",
    email: "dawnwzm@gmail.com",
    portfolio: "notion.so/2e6a3bff899180dd831cc11103d4d1fa",
  },
};
